### ISSUE TITLE
Please add a way to make some sites be a exception to the dark mode [REQUEST]

### ISSUE THREAD

**Issue by Noobao** [SoulBrowser/SoulBrowser#116]
When a site already has some sort of dark mode,color pallete,it turns into something similar to this.
 
Dark duckduck go on dark mode

![Screenshot_20220824-184550532](https://user-images.githubusercontent.com/84132367/186529432-400c18af-7e4b-4f57-983f-74c825604270.jpg)

Another example with a site that is dark by default,it looks like this

![Screenshot_20220824-185529522](https://user-images.githubusercontent.com/84132367/186530805-ee7571fe-8776-4368-b21d-153fee6f191f.jpg)

And the picture below show how it looks like when dark mode is activated.

![Screenshot_20220824-185517907](https://user-images.githubusercontent.com/84132367/186530884-5bce3474-a7de-40c0-9371-6a98de131b1d.jpg)

This behavior breaks the color of sites that uses dark colors by default,which makes very annoying having to switch it from dark to white and white to black,i assume that adding a exception to what sites will be applied the dark mode,or simply modify the dark mode in a way that doesn't make the colors turn whiter will fix this.

**Comment by kyoyacchi** [comment]
+1

**Comment by Noobao** [comment]
Works perfectly with the new webview, closing request.
