### ISSUE TITLE
Clean Mode: ads are not blocked/hidden

### ISSUE THREAD

**Issue by DiAnTTA** [SoulBrowser/SoulBrowser#58]
-- App 1.2.66, Android 10 -- 

**Steps to reproduce**
1. Turn on Clean Mode, add user filters: EasyList + [ABPVN List](https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt) 
2. Go to website http://m.lxhentai.com/
3. Ads (type image/gif) are not blocked/hidden

<details>
<summary>Screenshots</summary>

‌Soul Browser with Clean Mode | Firefox Browser with uBlock
|--------------|------------|
| ![Soul](https://user-images.githubusercontent.com/74956696/137376343-31248f49-d836-44e1-a82b-00cf38d87562.jpg) | ![IMG_20211014_174435](https://user-images.githubusercontent.com/74956696/137305212-3d9759f5-1ac0-4cde-b4d7-54e56d975114.jpg) |

</details>

**Comment by SoulBrowser** [comment]
Thank you very much. 😊

**Comment by kyoyacchi** [comment]
> Thank you very much. 😊

That bug is still same.  It doesn't block ads even though i add custom or local filters.
