### ISSUE TITLE
[Bug] Selection popup does not follow dark theme

### ISSUE THREAD

**Issue by emvaized** [SoulBrowser/SoulBrowser#90]
When "dark theme" is enabled in device settings and in Soul, text selection panel is still white.

![Screenshot_20220328-232206_Soul](https://user-images.githubusercontent.com/37851576/160480959-44ee9016-92c1-4e4c-8224-b574f0958135.jpg)

Example from Vivaldi browser where panel follows the dark theme:

![Screenshot_20220328-232316_Vivaldi Browser](https://user-images.githubusercontent.com/37851576/160481016-4e14835a-ae0f-49ab-adf2-a188e0c74b73.jpg)

**Comment by emvaized** [comment]
This problem is fixed in 1.3.12. Thanks!

**Comment by Noobao** [comment]
Bug is now fixed as of  1.3.33.
