### ISSUE TITLE
Add uBlock Origin to Soul Browser.

### ISSUE THREAD

**Issue by kyoyacchi** [SoulBrowser/SoulBrowser#97]
Hi. As far as i can see the filters in Clean Mode doesn't work, or some of them works , some of doesn't.

How about adding(/integrating) uBlock Origin to Soul Browser? It works well with Firefox and Kiwi Browsers.
or just adding extension support would be good.

**Comment by Hammoudi2299** [comment]
Adding extension like kiwi browser much better for me but that's up to you. 
For me i like adding other extensions like dopechat and more, because kiwi 
draining my device battery and ram thats why i love soul

**Comment by emvaized** [comment]
Extensions support was already requested [here](https://github.com/SoulBrowser/SoulBrowser/issues/36)
